version: "3.4"
services:
  echo-server:
    container_name: "echo-server"
    build:
      context: .
      target: base
      args:
        PORT: 8888
    command: "air"
    ports:
      - "8888:8888"
    volumes:
      - .:/go/app/base
    depends_on:
     - echo-db

  echo-db:
    container_name: "echo-db"
    image: postgres:14
    restart: always
    tty: true
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/data/echo-postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  echo-pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: mauroccvieira@gmail.com
      PGADMIN_DEFAULT_PASSWORD: maurinlol123
    ports:
      - "5050:80"