basePath: /
definitions:
  models.User:
    properties:
      id:
        type: integer
      name:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  requests.CreateUserRequest:
    properties:
      name:
        description: |-
          Name of the user
          required: true
        type: string
      password:
        description: |-
          Password of the user
          required: true
        type: string
      username:
        description: |-
          Username of the user
          required: true
        type: string
    required:
    - name
    - password
    - username
    type: object
  responses.CreateUserResponse:
    properties:
      id:
        type: integer
      name:
        type: string
      username:
        type: string
    type: object
  utils.Error:
    properties:
      message:
        type: string
    type: object
host: localhost:8888
info:
  contact: {}
  description: This is a sample server.
  termsOfService: http://swagger.io/terms/
  title: Go RestAPI API v1
  version: "1.0"
paths:
  /api/v1/user:
    get:
      consumes:
      - '*/*'
      description: Fetch a list of all users.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.User'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.Error'
      summary: Fetch a list of all users.
      tags:
      - User
    post:
      consumes:
      - application/json
      description: Create an user.
      parameters:
      - description: User
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/requests.CreateUserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/responses.CreateUserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.Error'
      summary: Create an user.
      tags:
      - User
schemes:
- http
swagger: "2.0"
