basePath: /
definitions:
  models.User:
    properties:
      id:
        type: integer
      name:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  utils.Error:
    properties:
      message:
        type: string
    type: object
host: localhost:8888
info:
  contact: {}
  description: This is a sample server.
  termsOfService: http://swagger.io/terms/
  title: Go RestAPI API v1
  version: "1.0"
paths:
  /api/v1/user:
    get:
      consumes:
      - '*/*'
      description: Fetch a list of all users.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.User'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.Error'
      summary: Fetch a list of all users.
      tags:
      - User
schemes:
- http
swagger: "2.0"
